In [1]:
import numpy as np

In [2]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [3]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [4]:
a = np.array([1,2,5,7,8])

In [5]:
a[2]=10

In [6]:
a

array([ 1,  2, 10,  7,  8])

In [8]:
np.arange(3,10)

array([3, 4, 5, 6, 7, 8, 9])

In [14]:
np.random.seed(42)
np.random.rand(5,2)

array([[0.37454012, 0.95071431],
       [0.73199394, 0.59865848],
       [0.15601864, 0.15599452],
       [0.05808361, 0.86617615],
       [0.60111501, 0.70807258]])

In [17]:
a = np.arange(5)

In [18]:
a

array([0, 1, 2, 3, 4])

In [5]:
u = np.array([2, 7, 5, 6])
v = np.array([3, 4, 8, 6])


In [6]:
def vector_vector_multiplication(u,v):
    assert u.shape[0] == v.shape[0]
    n = u.shape[0]
    result = 0.0
    for i in range(n):
        result = result + u[i]*v[i]
    return result
        
    

In [9]:
vector_vector_multiplication(u,v)

np.float64(110.0)

In [19]:
def matrix_vector_multiplication(u, v):
    assert u.shape[1] == v.shape[0]
    
    num_rows = u.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(u[i], v)
    
    return result

In [21]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result